### ISSUE TITLE
Redesign tutorial page to point to the HTML Tutorial, Tidbits and Resources page

### ISSUE THREAD

**Issue by gabiiiii-24-dev** [FrontEnd-ro/frontend.ro#311]
The first contact plays a very important role in a human's perception, so, the landing page should be more appealing, one idea of redesigning would be to get inspired by https://dribbble.com/shots/12163011-Online-Education-Platform but in place of the bear, to be an illustration of a persons that it's working on the laptop, or something like this.

**Comment by iampava** [comment]
I agree with you, a lot of pages on the website could use a redesign. I really love the dribble you sent, it's way nicer than our landing page. 

However, I think this task should be handled as part of a bigger Redesign Effort, so the new landing is in sync with all (most) other pages. Create a kind of design-system that we keep using throughout the website.

Some things I'd like to achieve with a redesign:
* website should be friendly, people should not be intimidated to start progamming
* custom illustrations (if possible) so we don't look like any other website. That's why if you look at the lessons, all the covers are "hand drawn" by us.

Coming back to the landing page, what do you think it's missing right now? Is it clear what we do, or should we add some more info? Maybe the login/register buttons right there? I'm asking because maybe we can tackle some small things first, before a full redesign.

**Comment by iampava** [comment]
Make sure to add Link to the "Resources" page
